# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package
on:
  # Trigger the workflow on pull request,
  pull_request:
    branches:
      - main

  # Trigger the workflow on push or pull request,
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  deploy:
    name: Build and deploy PyPi package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r requirements.txt
        pip install build

    - name: Build package
      run: |
        export VERSION="1.0.0"
        python -m build
    
    # Publish the package if this is a release or manual trigger
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}